----------------------------
-- DDL TABLA ETAPA
----------------------------
CREATE TABLE ETAPA (
  IDETAPA SERIAL  NOT NULL ,
  SIGUIENTEETAPA INTEGER    ,
  NOMBRE TEXT    ,
PRIMARY KEY(IDETAPA),
  FOREIGN KEY(SIGUIENTEETAPA)
    REFERENCES ETAPA(IDETAPA));

CREATE INDEX IFK_REL_08 ON ETAPA (SIGUIENTEETAPA);

----------------------------
-- DDL TABLA TIPOSANCION
----------------------------
CREATE TABLE TIPOSANCION (
  IDTIPOSANCION SERIAL  NOT NULL ,
  NOMBRETIPOSANCION TEXT      ,
PRIMARY KEY(IDTIPOSANCION));

----------------------------
-- DDL TABLA SERVICIO
----------------------------
CREATE TABLE Servicio (
  idServicio SERIAL NOT NULL,
  Nombre TEXT  NULL    ,
PRIMARY KEY(idServicio));

----------------------------
-- DDL TABLA USUARIO
----------------------------
CREATE TABLE USUARIOS (
  IDUSUARIO SERIAL  NOT NULL ,
  NOMBRE TEXT    ,
  APELLIDO TEXT,
  ROL INTEGER,
  CONTRASENA TEXT      ,
PRIMARY KEY(IDUSUARIO));

----------------------------
-- DDL TABLA ROL
----------------------------
CREATE TABLE Rol (
  idRol SERIAL  NOT NULL,
  DESCRIPCION TEXT  NULL    ,
PRIMARY KEY(idRol));

----------------------------
-- DDL TABLA ESTADO
----------------------------
CREATE TABLE ESTADO (
  IDESTADO SERIAL  NOT NULL ,
  NOMBREESTADO TEXT      ,
PRIMARY KEY(IDESTADO));

----------------------------
-- DDL TABLA CAUSAL
----------------------------
CREATE TABLE CAUSAL (
  IDCAUSAL SERIAL  NOT NULL ,
  NOMBRECAUSAL TEXT      ,
PRIMARY KEY(IDCAUSAL));

----------------------------
-- DDL TABLA DESCISIONRECURSO
----------------------------
CREATE TABLE DESCISIONRECURSO (
  IDDESCISIONRECURSO SERIAL  NOT NULL ,
  TIPODESCISIONRECURSO TEXT      ,
PRIMARY KEY(IDDESCISIONRECURSO));

----------------------------
-- DDL TABLA EMPRESA
----------------------------
CREATE TABLE EMPRESA (
  CONSECUTIVO SERIAL  NOT NULL ,
  IDEMPRESA INTEGER,
  NOMBRE TEXT    ,
  NIT INTEGER    ,
  SERVICIO INTEGER);

----------------------------
-- DDL TABLA PROCESO
----------------------------
CREATE TABLE PROCESO (
  IDPROCESO SERIAL  NOT NULL ,
  RADICADOPROCESO TEXT   NOT NULL ,
  USUARIOASIGNADO INTEGER   NOT NULL ,
  EMPRESA INTEGER   NOT NULL ,
  IDSERVICIO INTEGER NOT NULL,
  ESTADO INTEGER NOT NULL,
  TIPOSANCION INTEGER,
  DESCISIONRECURSO INTEGER,
  MONTOSANCION INTEGER      ,
  FECHACADUCIDAD timestamp with time zone      ,
PRIMARY KEY(IDPROCESO),
UNIQUE (RADICADOPROCESO),
  FOREIGN KEY(ESTADO)
    REFERENCES ESTADO(IDESTADO),
  FOREIGN KEY(USUARIOASIGNADO)
    REFERENCES USUARIOS(IDUSUARIO),
  FOREIGN KEY(DESCISIONRECURSO)
    REFERENCES DESCISIONRECURSO(IDDESCISIONRECURSO),
  FOREIGN KEY(TIPOSANCION)
    REFERENCES TIPOSANCION(IDTIPOSANCION));

CREATE INDEX IFK_REL_02 ON PROCESO (ESTADO);
CREATE INDEX IFK_REL_03 ON PROCESO (EMPRESA);
CREATE INDEX IFK_REL_07 ON PROCESO (USUARIOASIGNADO);
CREATE INDEX IFK_REL_08 ON PROCESO (DESCISIONRECURSO);
CREATE INDEX IFK_REL_09 ON PROCESO (TIPOSANCION);

----------------------------
-- DDL TABLA PROCESO_CAUSAL
----------------------------
CREATE TABLE PROCESO_CAUSAL (
  IDPROCESO INTEGER   NOT NULL ,
  IDCAUSAL INTEGER,
  FECHAHECHOS DATE    ,
  DESCRIPCION TEXT      ,
PRIMARY KEY(IDPROCESO),
  FOREIGN KEY(IDCAUSAL)
    REFERENCES CAUSAL(IDCAUSAL),
  FOREIGN KEY(IDPROCESO)
    REFERENCES PROCESO(IDPROCESO));

CREATE INDEX IFK_REL_11 ON PROCESO_CAUSAL (IDCAUSAL);
CREATE INDEX IFK_REL_10 ON PROCESO_CAUSAL (IDPROCESO);

----------------------------
-- DDL TABLA ETAPA_PROCESO
----------------------------
CREATE TABLE ETAPA_PROCESO (
  ETAPA INTEGER   NOT NULL ,
  PROCESO INTEGER   NOT NULL ,
  FECHAINICIOETAPA timestamp with time zone   NOT NULL ,
  FECHAFINETAPA timestamp with time zone    ,
  RADICADOETAPA TEXT   NOT NULL ,
  OBSERVACIONETAPA TEXT      ,
  TIPONOTIFICACION TEXT      ,
  fechaSiguienteEtapa DATE      ,
PRIMARY KEY(ETAPA, PROCESO),
  FOREIGN KEY(ETAPA)
    REFERENCES ETAPA(IDETAPA),
  FOREIGN KEY(PROCESO)
    REFERENCES PROCESO(IDPROCESO));

CREATE INDEX IFK_REL_04 ON ETAPA_PROCESO (ETAPA);
CREATE INDEX IFK_REL_05 ON ETAPA_PROCESO (PROCESO); 